import Head from "next/head";

import Header from "../components/header/Header";
import Trending from "../components/trending/Trending";
import Cryptocurrencies from "../components/cryptocurrencies/cryptocurrencies";
import GlobalCryptoInfo from "../components/globalCryptoInfo/GlobalCryptoInfo";

export default function Home() {
  return (
    <>
      <Head>
        <title>CoinMarketCap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </Head>
      <main>
        <GlobalCryptoInfo />
        <Header />
        <Trending />
        <Cryptocurrencies />
      </main>
    </>
  );
}
