import Head from "next/head";

import Header from "../components/header/Header";
import Trending from "../components/trending/Trending";
import Cryptocurrencies from "../components/cryptocurrencies/cryptocurrencies";

export default function Home() {
  return (
    <>
      <Head>
        <title>CoinMarketCap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Trending />
        <Cryptocurrencies />
      </main>
    </>
  );
}
